
# Importar : docker compose -f compose.yml -f compose_data.yml run --rm data-init
# Exportar : docker compose -f compose.yml -f compose_data.yml run --rm data-export
# Validar  : docker compose -f compose.yml -f compose_data.yml config

services:
  data-init:
    image: tryton/tryton:${VERSION:-latest}
    container_name: tryton-data-init
    depends_on:
      - postgres
      - server
    environment:
      DB_NAME: ${DB_NAME:-tryton}
      TRYTOND_CONFIG: /etc/trytond/trytond.conf
    volumes:
      - ./data:/data
      - ./python:/python
      - ./log:/log
    working_dir: /python
#   entrypoint: ["/bin/bash", "-c"]
    command: python3 auto_full_setup.py
