
# Importar : docker compose -f compose.yml -f compose_data.yml run --rm data-init
# Validar  : docker compose -f compose.yml -f compose_data.yml config

services:
  data-init:
    image: tryton/tryton:${VERSION:-latest}
    container_name: tryton-data-init
    networks: 
      - tryton_default
    # Nota: depends_on solo funciona si el servicio 'postgres' 
    # estuviera en este MISMO archivo. Como es externo, lo quitamos 
    # para evitar errores de validación. El script ya tiene reintentos.
    environment:
      DB_NAME: ${DB_NAME:-tryton}
      TRYTONPASSFILE: /tmp/.passwd
      TRYTOND_CONFIG: /config/trytond.conf
      TRYTOND_DATABASE_URI: "postgresql://postgres:clave1234@tryton-postgres-1:5432/"
    volumes:
      - ./config/.passwd:/tmp/.passwd
      - ./data:/data
      - ./log:/log
      - ./tmp:/tmp
      - ./config:/config
      - ./python:/python
    working_dir: /python
    entrypoint: ["/bin/sh", "-c"]
    command: ["python3 auto_full_setup.py"]

networks:  # <--- IMPORTANTE: Al mismo nivel que 'services'
  tryton_default:
    external: true