[database]
uri = postgresql://postgres:clave1234@tryton-postgres-1:5432/
path = /var/lib/trytond/db

[company]
name = Telepieza
currency = EUR
journal_name = Diario General
journal_code = GEN
vat_rates = 21,10,4

[web]
listen = 0.0.0.0:8000

[logging]
level = INFO
